create database grocery_db;
use grocery_db;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);
select * from Supplier;


-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
select * from categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);
select * from employees;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);
select * from customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
select * from products;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
select * from orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
select * from order_details;

# QUESTIONS

# 1. Customer Insights
# Gain an understanding of customer engagement and purchasing behavior.
--  How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;


--  Which customers have placed the highest number of orders?
SELECT c.cust_name,
       COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o 
  ON c.cust_id = o.cust_id
GROUP BY c.cust_name
ORDER BY total_orders DESC;



--  What is the total and average purchase value per customer?
SELECT c.cust_name,
       ROUND(SUM(od.total_price), 2) AS total_purchase_value,
       ROUND(AVG(od.total_price), 2) AS avg_purchase_value
FROM customers c
JOIN orders o 
  ON c.cust_id = o.cust_id
JOIN order_details od 
  ON o.ord_id = od.ord_id
GROUP BY c.cust_name
ORDER BY total_purchase_value DESC;



--  Who are the top 5 customers by total purchase amount?
SELECT c.cust_name,
       ROUND(SUM(od.total_price), 2) AS total_purchase_amount
FROM customers c
JOIN orders o 
  ON c.cust_id = o.cust_id
JOIN order_details od 
  ON o.ord_id = od.ord_id
GROUP BY c.cust_name
ORDER BY total_purchase_amount DESC
LIMIT 5;

#2. Product Performance
##Evaluate how well products are performing in terms of sales and revenue

-- How many products exist in each category?
SELECT c.cat_name,
       COUNT(p.prod_id) AS product_count
FROM categories c
JOIN products p
  ON c.cat_id = p.cat_id
GROUP BY c.cat_name
ORDER BY product_count DESC;


-- What is the average price of products by category?
SELECT c.cat_name,
       ROUND(AVG(p.price), 2) AS avg_product_price
FROM categories c
JOIN products p
  ON c.cat_id = p.cat_id
GROUP BY c.cat_name
ORDER BY avg_product_price DESC;


-- Which products have the highest total sales volume (by quantity)?
SELECT p.prod_name,
       SUM(od.quantity) AS total_quantity_sold
FROM products p
JOIN order_details od
  ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_quantity_sold DESC;


-- What is the total revenue generated by each product?
SELECT p.prod_name,
       ROUND(SUM(od.total_price), 2) AS total_revenue
FROM products p
JOIN order_details od
  ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_revenue DESC;


-- How do product sales vary by category and supplier?
SELECT c.cat_name, s.sup_name, SUM(od.total_price) revenue
FROM order_details od
JOIN products p ON od.prod_id=p.prod_id
JOIN categories c ON p.cat_id=c.cat_id
JOIN supplier s ON p.sup_id=s.sup_id
GROUP BY c.cat_name, s.sup_name;

##3. Sales and Order Trends
##Analyze business performance through orders and revenue over time.

-- How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;



-- What is the average value per order?
Select o.ord_id,avg(od.total_price) avg_value_per_order
from orders as o
join order_details as od
on o.ord_id = od.ord_id
group by o.ord_id
order by avg_value_per_order asc;



-- On which dates were the most orders placed?
SELECT 
    order_date,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;


-- What are the monthly trends in order volume and revenue?
SELECT 
    YEAR(order_date) AS order_year,
    MONTH(order_date) AS order_month,
    COUNT(order_id) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM orders
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY order_year, order_month;




-- How do order patterns vary across weekdays and weekends?
SELECT 
  IF(DAYOFWEEK(STR_TO_DATE(order_date,'%Y-%m-%d')) IN (1,7),
     'Weekend','Weekday') AS day_type,
  COUNT(*) AS orders
FROM orders
GROUP BY day_type;


##4.Supplier Contribution
##Identify the most active and profitable suppliers.

-- How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;


-- Which supplier provides the most products
SELECT s.sup_name, COUNT(p.prod_id) AS product_count
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name
ORDER BY product_count DESC
LIMIT 1;


-- What is the average price of products from each supplier?
SELECT s.sup_name, ROUND(AVG(p.price), 2) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name;


-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.sup_name, SUM(od.total_price) revenue
FROM supplier s
JOIN products p USING (sup_id)
JOIN order_details od USING (prod_id)
GROUP BY s.sup_name
ORDER BY revenue DESC
LIMIT 3;


## 5.Employee Performance
##Assess how employees are handling and influencing sales.

-- How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS employees_processed_orders
FROM orders;


-- Which employees have handled the most orders?
SELECT e.emp_name, COUNT(o.ord_id) AS orders_handled
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_name
ORDER BY orders_handled DESC;


-- What is the total sales value processed by each employee?
SELECT e.emp_name, ROUND(SUM(od.total_price), 2) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_name
ORDER BY total_sales DESC;


-- What is the average order value handled per employee?
SELECT e.emp_name,
       SUM(od.total_price)/COUNT(DISTINCT o.ord_id) AS avg_order
FROM employees e
JOIN orders o USING (emp_id)
JOIN order_details od USING (ord_id)
GROUP BY e.emp_name;


##6.Order Details Deep Dive
##Explore item-level sales patterns and pricing behavior.

-- What is the relationship between quantity ordered and total price?
SELECT quantity, SUM(total_price) AS total_sales
FROM order_details
GROUP BY quantity
ORDER BY quantity;


-- What is the average quantity ordered per product?
SELECT prod_id, ROUND(AVG(quantity), 2) AS avg_qty
FROM order_details
GROUP BY prod_id;


-- How does the unit price vary across products and orders?
SELECT prod_id, MIN(each_price) min_price, MAX(each_price) max_price
FROM order_details
GROUP BY prod_id;

select product_id,






